version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "_WLy_lbUbtWiC7Yzs-lA6SWfrirmOmlI"
      POSTGRES_DB: pod
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  timescaledb_cached:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb_cached
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "_WLy_lbUbtWiC7Yzs-lA6SWfrirmOmlI"
      POSTGRES_DB: pod_cached
    volumes:
      - timescaledb_cached_data:/var/lib/postgresql/data
      - ./timescaledb_cached.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  postgres_cached:
    image: postgres:16-alpine
    container_name: postgres_cached
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cached_database
    volumes:
      - postgres_cached_data:/var/lib/postgresql/data
      - ./postgresql_cached.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  timescaledb_data:
  timescaledb_cached_data:
  postgres_data:
  postgres_cached_data:
  mysql_data:
